name: Push to Development Branch

on:
  push:
    branches:
      - test

jobs:
  push_to_development:
    name: Push to Development Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch origin

      - name: Push to Development Branch
        run: |
          git checkout dev
          git push origin dev
