name: Test and Push

on:
  push:
    paths:
      - 'test_print.py'

jobs:
  test_and_push:
    name: Test and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest test_print.py

      - name: Push changes to dev branch
        if: ${{ success() }}
        run: |
          git config --global user.name "Ekram karim"
          git config --global user.email "Ekramkarim@hotmail.com"
          git push origin HEAD:dev
